branches:
  except: 
    - rpi
    - swift3

language: generic
sudo: required
env: SWIFT_VERSION=4.0

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9
      env:
        - OPENSSL_ROOT_DIR=$(brew --prefix openssl)

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  
  - echo "Installing libwebsockets...";
    git clone "https://github.com/warmcat/libwebsockets" || exit 3;
    pushd libwebsockets || exit 5;
    (cmake . && make && sudo make install) || exit 5;
    popd;
    sudo ldconfig

script:
  - swift test
